/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class github_com_ffmpegplayer_demo_PosixThread */

#ifndef _Included_github_com_ffmpegplayer_demo_PosixThread
#define _Included_github_com_ffmpegplayer_demo_PosixThread
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     github_com_ffmpegplayer_demo_PosixThread
 * Method:    pthread
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_github_com_ffmpegplayer_1demo_PosixThread_pthread
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
